language: java
notifications:
  hipchat:
    rooms:
      secure: cAsIpp3qU6VydHPTq5qQJLFeWFSgE1hkwCUqOZyMk/Tbbv8ApYZglJBRDfkjynbsQbAf+rSYDXxNLVQYsvDOfSiSYIVnKftZHX03EOZPzxTC+sfle1eiNI/FX6CqAj6y7NwOq7Q4BmX30phKgs0n6U2XmeUGFa38m4fro4wI217YtC42kDiHoNxvVcemLTdxv0LNkfktWVBxZua245Tz63kpyRbYhzMGahC4QEmWa8LJqLC2iWt9X2XJrF67xJb8mM446aMITotHfv/N34j+XY6pSlz7Ce5/ocvH5hy/U7zV7n5mGPJa7xgE4RRV9Nzm53iIuB4GjLWIjyhxl49VMlWYLf2g/bvpD8RkJQB2X7ME30QJWmYSKgIEkfD0YccZxbL+LgrmRjZDu7AdnEWm2FsoNQtLMJECm7L+zAZM4GjpdtQ5XIPDuQi0nB4n2TAf3xYynuQUbkimm+kRhti+UUEqvzF62Ul0y6mQ+bM4J8XXXiPpEp2j0xHtPHcamkF2UCx03Z8R2fLEYsNZuU8s/bk1fi0XVs1axzCzKolLgUjaN8gvyvWDzWbaD4B1oW9L0NBxcwEuAKXqNrExxoJcvtknbZHf1NIzI2bTyVfI6kEItMvEAfDaIj1q5epvB3uZZ1EkJWmpcpBiTZesYQ33gjqxrekMart3dia3NZ882QU=
deploy:
  provider: releases
  api_key:
    secure: Q3G9uOF2kMLnTVlvxuBNzPLJGHnEsxKouLORyweZ24+FMdj8l7JyRIWq35qiaJwhDHHhLsayAoJsAV1kV0sbwCajI94irXVmYFUcbsdFbBDOF+d4kLaaMeH8XAvGYQkuXNuvVGe+jcZg0g86VfeMBEKvdPNCXwJuYCkdc24+MUQcVi9H+sSQ4o9BsTLB7icskN/H0/phMLUpK8uU42PGSnoZVUNkMj75ogTiodi5VAMhl48iRn/6gg9ksCnP6VCJV9gjq9Oo7vA/syuHuZlIQInnMO5HbDSb/Xm4SwY8FwZ2PIKocubNFspEw7h83ygh+H7HWuctWBC2OgcZ9ZbDxVc83oIUVvzTTlJkwT28ZtSimHbyAmVSLGBgDoy0xW+f7lU40PX9Q+WHiDDrPZ1sv/SlLA3tqGRJdBV7QX4CBhAb/QJfXqoZjUIid0E9723vTOxAniO9STr03WFGpI3uZCm24NN3fel8LMFHVHP08QMURqYptdp9SmCg9JrdOZf3pTt+leA0v5jPf1STPYCNshdesAWwGCyrhSMRQQD9LD9k9x22kmZ0AlEKhd43AP+thsHBy8XnEm8pcgKYBWAdRTVNcfxqYyAQN8NLEnNPsjBy/kGD5rEqo3yGbibTvZj8dkmtbNlvttpFedSlkivX27VeHgyXXN7FSxNJvShXamQ=
  file: build/libs/xlr-splunk-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-splunk-plugin
